#!/usr/bin/env bash
# Installs and configures nginx

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

sudo hostnamectl set-hostname "$(head -1 /etc/hosts | cut -d' ' -f3)"

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    
    root /usr/share/nginx/html;
    index index.html index.htm;

    add_header X-Served-By $(hostname);

    location /redirect_me {
        return 301 http://google.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /usr/share/nginx/html;
      internal;
    }

}" > /etc/nginx/sites-available/default

service nginx restart
