#!/usr/bin/env bash
# This script display "Holberton School" 10 times using a while
c=1
while [ $c -lt 11 ] ; do
    echo "Holberton School"
    if [ $c -eq 9 ]; then
	 echo "Hi"
    fi
    c=$((c+1))
done
