#!/usr/bin/env bash
# This script display "Holberton School" 10 times using a while
c=0
while [ $c -le 9 ] ; do
    if [ $c -eq 9 ]; then
	 echo "Hi"
    fi
    echo "Holberton School"
    c=$((c+1))
done
