#!/usr/bin/env bash
# "bad luck" on 4th iteration "good luck" on 8th, otherwise "Holberton School"
c=0
while [ $c -lt 11 ]; do
    if [ $c -eq 4 ]; then
       echo "bad luck"
    elif [ $c -eq 8 ]; then
    	 echo "good luck"
    else
	echo "Holberton School"
    fi
    c=$((c+1))
done
