#!/usr/bin/env bash
# "bad luck" on 4th iteration "good luck" on 8th, otherwise "Holberton School"
for i in {1..10};
do
    if [ $i -eq 4 ]; then
       echo "bad luck"
    elif [ $i -eq 8 ]; then
    	 echo "good luck"
    else
	echo "Holberton School"
    fi
done
