#!/usr/bin/env bash
# On outputs 4,9, 17 display special output
c=1
while [ $c -le 20 ]; do
    echo $c
    case $c in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    c=$((c+1))
done
