#!/usr/bin/env bash
# Configures Ubuntu machine to use nginx
# Redirects /redirect_me/ to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sed -i '30 i\ \tlocation /redirect_me/ {\n\t\treturn 301 google.com;\n\t}\n' /etc/nginx/sites-enabled/default
service nginx restart
